# Default values for sock-shop.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
java:
    options: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
zipkin: 
    enabled:  false
    url: zipkin.zipkin.svc.cluster.local
frontend:
    replicas: 1
loadtest:
    replicas: 2
    enabled: false