apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: sock-shop
---
# apiVersion: rbac.authorization.k8s.io/v1beta1
# kind: ClusterRole
# metadata:
#   name: prometheus
#   namespace: sock-shop

# rules: []
# ---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-rules
  namespace: sock-shop
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: sock-shop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-rules
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: sock-shop
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: sock-shop
  namespace: sock-shop
  labels:
    app: microservices-demo
    prometheus: sock-shop
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: microservices-demo
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: sock-shop
  resources:
    requests:
      memory: 400Mi