apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: carts
  labels:
    app: carts
  namespace: sock-shop
spec:
  jobLabel: carts-metrics
  selector:
    matchLabels:
      app: carts
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
