apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  labels:
    app: microservices-demo
    component: catalogue
  namespace: sock-shop
spec:
  jobLabel: catalogue-metrics
  selector:
    matchLabels:
      app: catalogue
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
