apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  labels:
    app: microservices-demo
    component: front-end
  namespace: sock-shop
spec:
  jobLabel: front-end-metrics
  selector:
    matchLabels:
      app: front-end
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 8079
    path: /metrics
