apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment
  labels:
    app: microservices-demo
    component: payment
  namespace: sock-shop
spec:
  jobLabel: payment-metrics
  selector:
    matchLabels:
      app: payment
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
