apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user
  labels:
    app: microservices-demo
    component: user
  namespace: sock-shop
spec:
  jobLabel: user-metrics
  selector:
    matchLabels:
      app: user
  namespaceSelector:
    matchNames:
    - sock-shop
  endpoints:
  - targetPort: 80
    path: /metrics
